export const theme = {
  colors: {
    background: '#0a0f1e',
    backgroundLight: '#111827',
    backgroundCard: '#131a2e',
    backgroundModal: '#0d1424',
    accent: '#00ff88',
    accentDim: '#00cc6a',
    accentGlow: 'rgba(0, 255, 136, 0.15)',
    accentGlowStrong: 'rgba(0, 255, 136, 0.3)',
    text: '#e2e8f0',
    textMuted: '#94a3b8',
    textDim: '#64748b',
    border: '#1e293b',
    borderLight: '#334155',
    white: '#ffffff',
    danger: '#ef4444',
    warning: '#f59e0b',
    info: '#3b82f6',
    gold: '#ffd700',
    silver: '#c0c0c0',
    bronze: '#cd7f32',
  },
  fonts: {
    heading: "'JetBrains Mono', monospace",
    body: "'Inter', sans-serif",
  },
};

// Sample Data
export const sampleEvents = [
  {
    id: 'event-1',
    title: 'HackNest 2025',
    date: '2025-04-20',
    venue: 'Main Auditorium',
    type: 'Hackathon',
    status: 'past',
    description: 'Join us for our flagship 48-hour hackathon! Build innovative solutions, collaborate with talented developers, and compete for exciting prizes. Open to all skill levels. Teams of 2-4 members. Food, mentorship, and swag provided!',
    image: '/events/hacknest.jpg',
    registrationLink: '#',
  },
  {
    id: 'event-2',
    title: 'Web Dev Bootcamp',
    date: '2025-04-28',
    venue: 'Lab 3',
    type: 'Workshop',
    status: 'past',
    description: 'A comprehensive 3-day workshop covering modern web development from scratch. Learn HTML5, CSS3, JavaScript, React, and deploy your first full-stack application. Perfect for beginners looking to kick-start their web dev journey.',
    image: '/events/webdev.jpg',
    registrationLink: '#',
  },
  {
    id: 'event-3',
    title: 'CP Contest #12',
    date: '2025-05-05',
    venue: 'Online',
    type: 'Contest',
    status: 'past',
    description: 'Our monthly competitive programming contest featuring 6 problems of varying difficulty. Test your algorithmic skills against fellow coders. Prizes for top 3 performers. Rated on our internal leaderboard.',
    image: '/events/contest.jpg',
    registrationLink: '#',
  },
  {
    id: 'event-4',
    title: 'AI/ML Workshop Series',
    date: '2025-03-15',
    venue: 'Lab 1',
    type: 'Workshop',
    status: 'past',
    description: 'A 5-session series covering machine learning fundamentals, neural networks, and deploying ML models. Hands-on projects with real-world datasets.',
    image: '/events/aiml.jpg',
    registrationLink: '#',
  },
  {
    id: 'event-5',
    title: 'Open Source Contributions Talk',
    date: '2025-02-20',
    venue: 'Seminar Hall',
    type: 'Talk',
    status: 'past',
    description: 'Guest lecture by senior Google engineer on contributing to open source projects, building your developer portfolio, and getting started with GSoC.',
    image: '/events/opensource.jpg',
    registrationLink: '#',
  },
];

export const sampleProjects = [
  {
    id: 'proj-1',
    title: 'CampusNav',
    description: 'AR-based campus navigation app that helps students and visitors find their way around the NIELIT campus with augmented reality markers and real-time directions.',
    techStack: ['React Native', 'ARKit', 'Firebase', 'Node.js'],
    githubLink: 'https://github.com/devnest/campusnav',
    liveLink: 'https://campusnav.devnest.tech',
    contributors: ['Aryan Sharma', 'Priya Nair', 'Rahul Mehta'],
    image: '/projects/campusnav.jpg',
    status: 'approved',
  },
  {
    id: 'proj-2',
    title: 'CodeSync',
    description: 'Real-time collaborative code editor that allows multiple users to write, edit, and debug code simultaneously with built-in video chat and terminal sharing.',
    techStack: ['Next.js', 'Socket.io', 'Monaco Editor', 'Docker'],
    githubLink: 'https://github.com/devnest/codesync',
    liveLink: 'https://codesync.devnest.tech',
    contributors: ['Rahul Mehta', 'Karan Singh', 'Sneha Kapoor'],
    image: '/projects/codesync.jpg',
    status: 'approved',
  },
  {
    id: 'proj-3',
    title: 'AgriSense',
    description: 'IoT-powered crop monitoring dashboard that tracks soil moisture, temperature, and humidity in real-time to help farmers make data-driven decisions.',
    techStack: ['Python', 'React', 'MQTT', 'TensorFlow'],
    githubLink: 'https://github.com/devnest/agrisense',
    liveLink: 'https://agrisense.devnest.tech',
    contributors: ['Priya Nair', 'Aryan Sharma'],
    image: '/projects/agrisense.jpg',
    status: 'approved',
  },
  {
    id: 'proj-4',
    title: 'StudyBuddy',
    description: 'AI-powered study companion that generates flashcards, quizzes, and summaries from lecture notes and textbook PDFs using NLP.',
    techStack: ['Python', 'FastAPI', 'React', 'OpenAI'],
    githubLink: 'https://github.com/devnest/studybuddy',
    liveLink: 'https://studybuddy.devnest.tech',
    contributors: ['Sneha Kapoor', 'Karan Singh'],
    image: '/projects/studybuddy.jpg',
    status: 'approved',
  },
];

export const sampleBlogs = [
  {
    id: 'blog-1',
    slug: 'how-i-cracked-gsoc',
    title: 'How I Cracked Google Summer of Code',
    author: 'Aryan Sharma',
    date: '2025-03-15',
    tags: ['Career', 'Open Source'],
    readTime: '8 min read',
    thumbnail: '/blog/gsoc.jpg',
    status: 'approved',
    excerpt: 'My complete journey from a beginner to getting selected for GSoC 2024. Tips, resources, and the strategy that worked for me.',
    content: `Getting selected for Google Summer of Code was a dream that took me two attempts to achieve. Here's my complete journey and the lessons I learned along the way.\n\n## Starting Out\n\nI first heard about GSoC in my second year of college. Like most beginners, I was overwhelmed by the idea of contributing to open source. The codebases seemed massive, the community intimidating, and the application process confusing.\n\n## The Failed Attempt\n\nIn my first attempt, I made the classic mistake of starting too late. I began looking at organizations only after the list was announced, rushed through a mediocre proposal, and predictably wasn't selected.\n\n## What Changed\n\nAfter my first failure, I took a systematic approach:\n\n1. **Started early**: I began contributing to open source 6 months before GSoC\n2. **Picked the right org**: Instead of chasing popular organizations, I found one that aligned with my skills\n3. **Built relationships**: I became an active community member, not just a code contributor\n4. **Wrote a killer proposal**: I spent 3 weeks refining my proposal with mentor feedback\n\n## Key Tips\n\n- Start contributing to open source TODAY, not when GSoC season begins\n- Quality over quantity - one meaningful PR is worth more than ten typo fixes\n- Communication is key - be active on the community's chat channels\n- Your proposal should show understanding of the project, not just technical skills\n\n## Resources\n\n- GSoC official guide\n- First Contributions repository\n- Good First Issues aggregator\n\nRemember, GSoC is not just about coding - it's about becoming part of a community. Focus on learning and contributing genuinely, and the selection will follow.`,
  },
  {
    id: 'blog-2',
    slug: 'getting-started-with-cp',
    title: 'Getting Started with Competitive Programming',
    author: 'Priya Nair',
    date: '2025-03-01',
    tags: ['CP', 'DSA'],
    readTime: '6 min read',
    thumbnail: '/blog/cp.jpg',
    status: 'approved',
    excerpt: 'A beginner-friendly guide to competitive programming. Learn the fundamentals, choose the right platforms, and build a practice routine.',
    content: `Competitive programming can seem daunting at first, but with the right approach, anyone can get started and improve steadily.\n\n## What is Competitive Programming?\n\nCompetitive programming (CP) is the sport of solving well-defined algorithmic problems within time constraints. It sharpens your problem-solving skills, data structure knowledge, and coding speed.\n\n## Getting Started\n\n### Choose Your Language\nC++ is the most popular choice due to its speed and STL library. Python works for beginners but may cause TLE on harder problems. Java is a solid middle ground.\n\n### Learn the Basics\n1. **Arrays and Strings**: Start here - most beginner problems use these\n2. **Sorting and Searching**: Binary search is your best friend\n3. **Basic Math**: GCD, primes, modular arithmetic\n4. **Recursion**: Foundation for dynamic programming\n\n### Platforms to Practice\n- **Codeforces**: Best for contests and problem variety\n- **LeetCode**: Great for interview prep and structured learning\n- **CodeChef**: Good beginner contests (Starters)\n- **AtCoder**: Clean problems with great editorials\n\n## Building a Routine\n\n- Solve 2-3 problems daily\n- Participate in at least one contest per week\n- After each contest, upsolve problems you couldn't solve\n- Read editorials and learn new techniques\n\n## Common Mistakes to Avoid\n\n- Don't just read solutions without trying first\n- Don't skip the basics to jump to advanced topics\n- Don't compare your progress with others\n\nThe journey of a thousand ratings begins with a single AC. Happy coding!`,
  },
  {
    id: 'blog-3',
    slug: 'building-rest-api-nodejs',
    title: 'Building Your First REST API in Node.js',
    author: 'Rahul Mehta',
    date: '2025-02-15',
    tags: ['Web Dev', 'Backend'],
    readTime: '10 min read',
    thumbnail: '/blog/nodejs.jpg',
    status: 'approved',
    excerpt: 'Step-by-step tutorial to build a complete REST API using Node.js and Express with MongoDB integration.',
    content: `In this tutorial, we'll build a complete REST API from scratch using Node.js, Express, and MongoDB.\n\n## Prerequisites\n\n- Node.js installed (v18+)\n- Basic JavaScript knowledge\n- MongoDB Atlas account (free tier)\n\n## Setting Up\n\n\`\`\`bash\nmkdir my-api && cd my-api\nnpm init -y\nnpm install express mongoose dotenv cors\nnpm install -D nodemon\n\`\`\`\n\n## Creating the Server\n\nCreate \`server.js\`:\n\n\`\`\`javascript\nconst express = require('express');\nconst mongoose = require('mongoose');\nconst cors = require('cors');\nrequire('dotenv').config();\n\nconst app = express();\napp.use(cors());\napp.use(express.json());\n\nmongoose.connect(process.env.MONGODB_URI);\n\napp.listen(3000, () => console.log('Server running on port 3000'));\n\`\`\`\n\n## Defining Models\n\nCreate a \`models/Task.js\`:\n\n\`\`\`javascript\nconst mongoose = require('mongoose');\n\nconst taskSchema = new mongoose.Schema({\n  title: { type: String, required: true },\n  completed: { type: Boolean, default: false },\n  createdAt: { type: Date, default: Date.now }\n});\n\nmodule.exports = mongoose.model('Task', taskSchema);\n\`\`\`\n\n## CRUD Routes\n\nImplement all four CRUD operations:\n- **POST** /tasks - Create a task\n- **GET** /tasks - Read all tasks\n- **PUT** /tasks/:id - Update a task\n- **DELETE** /tasks/:id - Delete a task\n\n## Testing\n\nUse Postman or Thunder Client to test your endpoints. Make sure each route returns appropriate status codes and error messages.\n\n## Next Steps\n\n- Add authentication with JWT\n- Implement pagination\n- Add input validation with Joi\n- Deploy to Railway or Render\n\nCongratulations! You've built your first REST API. The skills you've learned here form the foundation of backend development.`,
  },
];

export const sampleMembers = {
  core: [
    {
      id: 'member-1',
      name: 'Aryan Sharma',
      role: 'President',
      bio: 'Full-stack developer and open source enthusiast. GSoC 2024 contributor. Passionate about building products that make a difference.',
      github: 'https://github.com/aryansharma',
      linkedin: 'https://linkedin.com/in/aryansharma',
      batch: '2022-2026',
    },
    {
      id: 'member-2',
      name: 'Priya Nair',
      role: 'Vice President',
      bio: 'Competitive programmer and ML researcher. Expert rated on Codeforces. Loves solving complex algorithmic problems.',
      github: 'https://github.com/priyanair',
      linkedin: 'https://linkedin.com/in/priyanair',
      batch: '2022-2026',
    },
    {
      id: 'member-3',
      name: 'Rahul Mehta',
      role: 'Tech Lead',
      bio: 'Backend wizard. Specializes in distributed systems and cloud architecture. Built multiple production-grade APIs.',
      github: 'https://github.com/rahulmehta',
      linkedin: 'https://linkedin.com/in/rahulmehta',
      batch: '2022-2026',
    },
    {
      id: 'member-4',
      name: 'Sneha Kapoor',
      role: 'Design Lead',
      bio: 'UI/UX designer and frontend developer. Creates pixel-perfect interfaces with a focus on user experience and accessibility.',
      github: 'https://github.com/snehakapoor',
      linkedin: 'https://linkedin.com/in/snehakapoor',
      batch: '2023-2027',
    },
    {
      id: 'member-5',
      name: 'Karan Singh',
      role: 'Social Media Lead',
      bio: 'Content creator and community manager. Handles all DevNest social media and outreach. Also a Python enthusiast.',
      github: 'https://github.com/karansingh',
      linkedin: 'https://linkedin.com/in/karansingh',
      batch: '2023-2027',
    },
  ],
  general: [
    { id: 'gen-1', name: 'Ananya Gupta', batch: '2023-2027', github: '#' },
    { id: 'gen-2', name: 'Vikram Reddy', batch: '2023-2027', github: '#' },
    { id: 'gen-3', name: 'Meera Joshi', batch: '2024-2028', github: '#' },
    { id: 'gen-4', name: 'Rohan Desai', batch: '2024-2028', github: '#' },
    { id: 'gen-5', name: 'Isha Verma', batch: '2022-2026', github: '#' },
    { id: 'gen-6', name: 'Aditya Kumar', batch: '2023-2027', github: '#' },
    { id: 'gen-7', name: 'Nisha Patel', batch: '2024-2028', github: '#' },
    { id: 'gen-8', name: 'Sameer Khan', batch: '2022-2026', github: '#' },
  ],
  alumni: [
    { id: 'alum-1', name: 'Dr. Aarav Menon', batch: '2018-2022', achievement: 'SDE @ Google', github: '#', linkedin: '#' },
    { id: 'alum-2', name: 'Kavya Iyer', batch: '2019-2023', achievement: 'ML Engineer @ Microsoft', github: '#', linkedin: '#' },
    { id: 'alum-3', name: 'Harsh Pandey', batch: '2019-2023', achievement: 'Founder, TechStartup', github: '#', linkedin: '#' },
  ],
};

export const leaderboardData = [
  { rank: 1, name: 'Priya Nair', codeforcesRating: 1847, leetcodeProblems: 520, codechefStars: 5, totalScore: 2850 },
  { rank: 2, name: 'Aryan Sharma', codeforcesRating: 1654, leetcodeProblems: 430, codechefStars: 4, totalScore: 2500 },
  { rank: 3, name: 'Rahul Mehta', codeforcesRating: 1520, leetcodeProblems: 380, codechefStars: 4, totalScore: 2280 },
  { rank: 4, name: 'Vikram Reddy', codeforcesRating: 1450, leetcodeProblems: 350, codechefStars: 3, totalScore: 2100 },
  { rank: 5, name: 'Ananya Gupta', codeforcesRating: 1380, leetcodeProblems: 310, codechefStars: 3, totalScore: 1950 },
  { rank: 6, name: 'Karan Singh', codeforcesRating: 1290, leetcodeProblems: 280, codechefStars: 3, totalScore: 1800 },
  { rank: 7, name: 'Meera Joshi', codeforcesRating: 1250, leetcodeProblems: 260, codechefStars: 2, totalScore: 1700 },
  { rank: 8, name: 'Rohan Desai', codeforcesRating: 1180, leetcodeProblems: 230, codechefStars: 2, totalScore: 1550 },
  { rank: 9, name: 'Isha Verma', codeforcesRating: 1120, leetcodeProblems: 200, codechefStars: 2, totalScore: 1420 },
  { rank: 10, name: 'Aditya Kumar', codeforcesRating: 1050, leetcodeProblems: 180, codechefStars: 2, totalScore: 1300 },
];

export const faqData = [
  {
    question: 'Who can join DevNest?',
    answer: 'DevNest is open to all students of NIELIT, regardless of their branch or year. Whether you\'re a complete beginner or an experienced programmer, there\'s a place for you here.',
  },
  {
    question: 'How do I become a member?',
    answer: 'Simply fill out the registration form on our website or reach out to any core committee member. We also conduct an orientation session at the beginning of each academic year.',
  },
  {
    question: 'Do I need prior coding experience?',
    answer: 'Not at all! We welcome beginners and conduct regular workshops starting from the basics. Our mentorship program pairs newcomers with experienced members.',
  },
  {
    question: 'How often are events held?',
    answer: 'We host 2-3 events per month, including weekly CP contests, monthly workshops, and quarterly hackathons. Check our events page for the latest schedule.',
  },
  {
    question: 'Can I contribute to club projects?',
    answer: 'Absolutely! All our projects are open source and we encourage contributions. Visit our Projects page, pick a project that interests you, and check the GitHub repo for contribution guidelines.',
  },
  {
    question: 'Is there a membership fee?',
    answer: 'No, DevNest membership is completely free. We believe in making tech education accessible to everyone. Some premium events may have a nominal fee to cover costs.',
  },
];

export const achievements = [
  // '🏆 1st Place - National Hackathon 2024',
  // '🥇 Top 10 in ICPC Regionals',
  // '💻 50+ Open Source Contributions',
  // '🎓 15 GSoC Selections',
  // '🌟 500+ Active Members',
  // '📈 100+ Events Hosted',
  // '🤝 Industry Partnerships with 10+ Companies',
  // '🏅 Best Coding Club Award - NIELIT 2024',
];
